### ISSUE TITLE
Battery on the top right does not reflect the actual battery status

### ISSUE THREAD

**Issue by shoeper** [NicoHood/arc-theme#103]
The battery indicator on the top right always stays at 100% although my battery is at e.g. 60%. Something that came to my mind today is that it could have to do with my thinkpad having 2 batteries. The percentage indicator next to the battery is correct, though. Maybe just the value of the main battery is being taken (which is the small internal one) which is being used when the bigger - hot swappable - one is empty or removed. In this case I think it would be better to use the combined battery status.

See this screenshot:
![screenshot from 2018-08-09 22-08-03](https://user-images.githubusercontent.com/5340585/43923647-aac7e7e8-9c22-11e8-8d7b-0064d4d841a7.png)

### Details

- Distribution (with version):
```
~ cat /etc/fedora-release 
Fedora release 28 (Twenty Eight)
```

- Desktop environment (with version):
```
~ gnome-shell --version
GNOME Shell 3.28.3
```

- Arc version/commit (don't put "latest"):
I've had this issue since using arc-theme with multiple releases. I've updated within the last month, I don't know how to find out the commit as I've removed the source already. I've followed the PRs and haven't seen anything that could've fixed this in the meantime.

- GTK+ 3 version: 3.22.30

- Murrine engine version:
```
Name         : gtk-murrine-engine
Version      : 0.98.2
Release      : 14.fc28
Arch         : x86_64
```

  - `gnome-themes-standard` version: could only find gnome-themes-extra
```
Name         : gnome-themes-extra
Version      : 3.28
Release      : 1.fc28
Arch         : x86_64
```

- Installation method (package or source): source

**Comment by shoeper** [comment]
Now something unexpected happened (yes the issue is there since I use arc-theme, but I didn't have a closer look at it so far). The battery is now at 56% and the battery indicator is below 100 but does neither match the main, nor the extra battery and also not the total percentage.

See this screenshot (have a look at the indicator on the top right):
![screenshot from 2018-08-09 22-49-37](https://user-images.githubusercontent.com/5340585/43925149-c98442e0-9c26-11e8-9909-0f12a1f31c36.png)

**Comment by NicoHood** [comment]
That is strange. Does it also happen with other themes? I must admit, I never really looked at this icon, and my laptop is always plugged in. But I will keep a look at it.

**Comment by shoeper** [comment]
With the default scheme I'm very sure this did not happen.

**Comment by shoeper** [comment]
So, it looks like the issue is somewhere in the Arc icon theme.

I've done some screenshots at around 50 percent with the gnome default scheme (adwaita and arc). Only the icon theme affects the look of the battery indicator.

With arc theme:
![screenshot from 2018-08-15 18-35-21](https://user-images.githubusercontent.com/5340585/44160339-67c31700-a0ba-11e8-95c7-582774d62f77.png)

With adwaita:
![screenshot from 2018-08-15 18-33-47](https://user-images.githubusercontent.com/5340585/44160353-77daf680-a0ba-11e8-9524-75444a3da300.png)

With arc theme but adwaita icon theme:
![screenshot from 2018-08-15 18-35-09](https://user-images.githubusercontent.com/5340585/44160383-8c1ef380-a0ba-11e8-90ff-567252c24535.png)

**Comment by shoeper** [comment]
Looking into it deeper confirms my observation.

The issue seems to be that battery-good.svg and battery-medium.svg are the same file (same md5sum) while battery-medium should reflect 60% battery it actually reflects 80% battery.

**Comment by shoeper** [comment]
battery-low.svg also seems to reflect a better loaded battery than it actually is (looks like 50% while it is being used for 40 and less)

**Comment by shoeper** [comment]
This would be better in my opinion:
![battery-medium svg](https://user-images.githubusercontent.com/5340585/44161654-46fcc080-a0be-11e8-97f6-3d4f1e55683f.png)

**Comment by shoeper** [comment]
Looking closer at it the icon-theme currently seems not to be part of your fork and the specific issue has been fixed here: https://github.com/horst3180/arc-icon-theme

**Comment by shoeper** [comment]
Maybe you can fork the icon theme as well and merge (some) of the 5 PRs.

**Comment by shoeper** [comment]
I've now merged https://github.com/horst3180/arc-icon-theme/pull/22, https://github.com/horst3180/arc-icon-theme/pull/46 and https://github.com/horst3180/arc-icon-theme/pull/48 locally and after installing with pr22 merged the issue seems to be fixed. I'll push it later.

**Comment by shoeper** [comment]
I've pushed the current state to https://github.com/arc-theme/arc-icon-theme

**Comment by NicoHood** [comment]
You are right, I am going to fork the icon theme and also apply patches there. But it will take me some time, please be patient.

**Comment by shoeper** [comment]
You can just copy the repo above if you want.

**Comment by NicoHood** [comment]
@shoeper Can you please create a PR to https://github.com/NicoHood/arc-icon-theme

**Comment by shoeper** [comment]
I've created a PR merging several PRs from the old upstream.

**Comment by shoeper** [comment]
See https://github.com/NicoHood/arc-icon-theme/pull/1

Maybe it would be good to either enable the issue tracker for arc icon theme as well or link to this issue tracker from the description.

Closing this as it's fixed with the PR above.

**Comment by evenfrost** [comment]
![Screenshot from 2019-06-24 15-06-30](https://user-images.githubusercontent.com/3055750/60017573-b6a1eb80-9691-11e9-9a9d-58d5496aaa33.png)

@NicoHood @shoeper seems the bug is still here.

Arc theme version string:
```
arc-theme/disco,disco,now 20190330+201905200231~ubuntu19.04.1 all
```

**Comment by shoeper** [comment]
Yes, obviously. My PR has been rejected. Maybe you want to split it up to get it merged.

**Comment by evenfrost** [comment]
Just FYI, this seems fixed in Ubuntu 19.10 with latest arc-theme.
